[versions]
junit = "4.13.2"
jetbrainsKotlin = "2.1.0"
kotlinpoet = "2.0.0"
ksp = "2.1.0-1.0.29"
jvm = "17"

[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }
ksp-api = { group = "com.google.devtools.ksp", name = "symbol-processing-api", version.ref = "ksp" }
kotlinpoet = { group = "com.squareup", name = "kotlinpoet", version.ref = "kotlinpoet" }
kotlinpoet-ksp = { group = "com.squareup", name = "kotlinpoet-ksp", version.ref = "kotlinpoet" }
compiletesting = { group = "dev.zacsweers.kctfork", name = "ksp", version = "0.7.0" }
mockk = { group = "io.mockk", name = "mockk", version = "1.13.13" }
coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version = "1.9.0" }

[plugins]
ksp-plugin = { id = "com.google.devtools.ksp", version.ref = "ksp" }
jetbrainsKotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "jetbrainsKotlin" }
jetbrainsKotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "jetbrainsKotlin" }
mavenPublish = { id = "com.vanniktech.maven.publish", version = "0.30.0" }
