[versions]
junit = "4.13.2"
jetbrainsKotlin = "2.3.10"
kotlinpoet = "2.2.0"
ksp = "2.3.5"
jvm = "21"
agp = "9.0.0"

[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }
assertj = { group = "org.assertj", name = "assertj-core", version = "3.27.7" }
ksp-api = { group = "com.google.devtools.ksp", name = "symbol-processing-api", version.ref = "ksp" }
kotlin-compiler = { group = "org.jetbrains.kotlin", name = "kotlin-compiler", version.ref = "jetbrainsKotlin" }
kotlinpoet = { group = "com.squareup", name = "kotlinpoet", version.ref = "kotlinpoet" }
kotlinpoet-ksp = { group = "com.squareup", name = "kotlinpoet-ksp", version.ref = "kotlinpoet" }
compiletesting = { group = "dev.zacsweers.kctfork", name = "ksp", version = "0.12.1" }
mockk = { group = "io.mockk", name = "mockk", version = "1.14.9" }
coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version = "1.10.2" }
kotlin-reflect = { group = "org.jetbrains.kotlin", name = "kotlin-reflect", version.ref = "jetbrainsKotlin" }
kotlin-gradle = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "jetbrainsKotlin" }
kotlin-test = { group = "org.jetbrains.kotlin", name = "kotlin-test", version.ref = "jetbrainsKotlin" }
robolectric = { group = "org.robolectric", name = "robolectric", version = "4.16.1" }
androidx-test = { group = "androidx.test.ext", name = "junit", version = "1.3.0" }

[plugins]
ksp-plugin = { id = "com.google.devtools.ksp", version.ref = "ksp" }
gradle-publish = { id = "com.gradle.plugin-publish", version = "2.0.0" }
jetbrainsKotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "jetbrainsKotlin" }
jetbrainsKotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "jetbrainsKotlin" }
mavenPublish = { id = "com.vanniktech.maven.publish", version = "0.36.0" }
buildconfig = { id = "com.github.gmazzo.buildconfig", version = "6.0.7" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "jetbrainsKotlin" }
